---
env:
  - CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C link-arg=-fuse-ld=mold"
  - CCACHE_DIR="/var/cache/ccache"
  - FEATURES="ccache"
  - LDFLAGS="${LDFLAGS} -fuse-ld=mold"
  - RUSTC_WRAPPER=/usr/bin/sccache
  - SCCACHE_DIR=/var/cache/sccache
  - SCCACHE_MAX_FRAME_LENGTH=104857600

packages:
  - app-admin/ansible
  - app-admin/ansible-lint
  - app-admin/sudo
  - app-admin/sysklogd
  - app-editors/vim
  - app-misc/tmux
  - app-misc/zellij
  - app-shells/bash-completion
  - app-shells/dash
  - app-shells/fish
  - app-shells/gentoo-zsh-completions
  - app-shells/nushell
  - app-shells/starship
  - app-shells/zsh
  - dev-util/ccache
  - dev-util/github-cli
  - dev-util/sccache
  - gui-apps/foot
  - gui-apps/swayidle
  - gui-apps/swaylock
  - gui-apps/wofi
  - gui-wm/sway
  - media-fonts/noto
  - media-fonts/noto-emoji
  - net-firewall/nftables
  - net-misc/chrony
  - net-wireless/iwd
  - sys-boot/grub
  - sys-devel/mold
  - sys-firmware/intel-microcode
  - sys-kernel/gentoo-kernel-bin
  - sys-kernel/linux-firmware
  - sys-process/cronie
  - www-client/firefox-bin
  - www-client/google-chrome
  - x11-terms/alacritty
  - x11-terms/kitty

license:
  - 'sys-firmware/intel-microcode intel-ucode'
  - 'sys-kernel/linux-firmware @BINARY-REDISTRIBUTABLE'
  - 'www-client/google-chrome google-chrome'

mask:
  - 'dev-lang/rust'

use:
  - 'app-editors/vim python'
  - 'app-shells/dash libedit'
  - 'gui-wm/sway grimshot'
  - 'gui-wm/sway tray'
  - 'gui-wm/sway wallpapers'
  - 'media-fonts/noto cjk'
  - 'media-fonts/noto-emoji icons'
  - 'net-wireless/iwd standalone'
  - 'sys-auth/seatd builtin'
  - 'sys-auth/seatd server'
  - 'www-client/firefox-bin wayland'
  - 'x11-terms/alacritty -X'
  - 'x11-terms/alacritty wayland'
  - 'x11-terms/kitty -X'
  - 'x11-terms/kitty wayland'
