---
packages:
  - app-admin/ansible
  - app-admin/ansible-lint
  - app-admin/sudo
  - app-admin/sysklogd
  - app-editors/vim
  - app-misc/tmux
  - app-shells/bash-completion
  - app-shells/dash
  - app-shells/gentoo-zsh-completions
  - app-shells/zsh
  - dev-util/ccache
  - dev-util/github-cli
  - dev-util/sccache
  - gui-apps/foot
  - gui-apps/swayidle
  - gui-apps/swaylock
  - gui-apps/wofi
  - gui-wm/sway
  - media-fonts/noto
  - media-fonts/noto-emoji
  - net-firewall/nftables
  - net-misc/chrony
  - net-wireless/iwd
  - sys-boot/grub
  - sys-devel/mold
  - sys-firmware/intel-microcode
  - sys-kernel/gentoo-kernel-bin
  - sys-kernel/linux-firmware
  - sys-process/cronie
  - www-client/firefox-bin
  - www-client/google-chrome
