---
- name: Provisioning
  hosts: localhost
  roles:
    - {role: locale, tags: [locale]}
    - {role: package, tags: [package]}
    - {role: service, tags: [service]}
    - {role: user, tags: [user]}
