---
version: '3'

tasks:
  default:
    cmds:
      - task: lint
      - task: play
  play:
    deps:
      - check
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml -K
  lint:
    deps:
      - check
    cmds:
      - ansible-lint
  check:
    run: once
    internal: true
    deps:
      - yamllint
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml -K --check --diff
  yamllint:
    run: once
    internal: true
    cmds:
      - yamllint .
