---
version: '3'

tasks:
  default:
    cmds:
      - task: play
      - task: lint
  play:
    deps:
      - check
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml -K
  lint:
    deps:
      - check
    cmds:
      - ansible-lint --offline
  check:
    run: once
    internal: true
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml -K --check --diff
