---
version: '3'

tasks:
  default:
    deps:
      - play
  play:
    deps:
      - lint
    cmds:
      - ansible-playbook -i inventory.yml playbook.yml -K
  lint:
    cmds:
      - ansible-lint --offline playbook.yml
