---
- name: Install
  ansible.builtin.include_role:
    name: package
  vars:
    package_list: '{{ git_packages }}'
    package_state: '{{ git_package_state }}'
    package_make_conf: '{{ git_make_conf }}'
    package_accept_keywords: '{{ git_package_accept_keywords }}'
    package_env: '{{ git_package_env }}'
    package_license: '{{ git_package_license }}'
    package_mask: '{{ git_package_mask }}'
    package_use: '{{ git_package_use }}'

- name: Gitconfig
  community.general.ini_file:
    path: '{{ ansible_env.HOME }}/.gitconfig'
    mode: '0644'
    section: include
    option: path
    value: .config/git/config
    state: '{{ git_package_state }}'

- name: Link Config
  ansible.builtin.include_role:
    name: user
    tasks_from: config
  vars:
    user_config_state: '{{ git_config_state }}'
    user_config:
      - git
