---
- name: Include_task
  ansible.builtin.include_tasks:
    file: group.yml

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.profile'
    line: 'export {{ item }}'
    insertbefore: '# BEGIN ANSIBLE MANAGED BLOCK'
  with_items:
    - '{{ env }}'

- name: Blockinfile
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}'
    create: true
    mode: '0644'
    block: '{{ lookup("vars", item).block }}'
    marker: '{{ lookup("vars", item).marker }}'
  with_items:
    - bash_profile
    - vimrc
    - zshenv
    - profile

- name: Gitconfig
  community.general.ini_file:
    path: '{{ ansible_env.HOME }}/.gitconfig'
    mode: '0644'
    section: include
    option: path
    value: .config/git/config

- name: EnsureDir
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config'
    state: directory

- name: Link Config
  ansible.builtin.file:
    dest: '{{ ansible_env.HOME }}/.config/{{ item }}'
    src: '{{ role_path }}/files/config/{{ item }}'
    state: link
  with_items:
    - '{{ config }}'

- name: Update config
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/main.yml'
    line: '  - {{ item }}'
    insertafter: 'config:'
  with_lines:
    - ls --almost-all '{{ ansible_env.HOME }}/.config'
    - ls --almost-all '{{ role_path }}/files/config'
