---
- name: Include_task
  ansible.builtin.include_tasks:
    file: group.yml

- name: Update env
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.profile'
    line: 'export {{ item }}'
    insertbefore: '# BEGIN ANSIBLE MANAGED BLOCK'
  with_items:
    - '{{ user_env }}'

- name: Blockinfile
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}'
    create: true
    mode: '0644'
    block: '{{ lookup("vars", "user_" + item).block }}'
    marker: '{{ lookup("vars", "user_" + item).marker }}'
  with_items:
    - bash_profile
    - profile
    - vimrc
    - zshenv

- name: Ensure $HOME/.config
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config'
    mode: '0755'
    state: directory

- name: Link Config
  ansible.builtin.file:
    dest: '{{ ansible_env.HOME }}/.config/{{ item }}'
    src: '{{ role_path }}/files/config/{{ item }}'
    state: link
  with_items:
    - '{{ user_config }}'
