---
- name: Group
  ansible.builtin.user:
    name: '{{ ansible_env.USER }}'
    groups: '{{ item }}'
    append: true
  with_items:
    - '{{ group }}'

- name: '{{ item }}'
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.{{ item }}'
    create: true
    block: '{{ lookup("vars", item).block }}'
    marker: '{{ lookup("vars", item).marker }}'
  with_items:
    - bash_profile
    - vimrc
    - zshenv

- name: '{{ task }}'
  ansible.builtin.include_tasks:
    file: dotfiles.yml
