---
- name: Install
  ansible.builtin.package:
    name: '{{ item }}'
  with_items:
    - '{{ packages }}'
  become: true

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/main.yml'
    line: '  - {{ item }}'
    insertafter: 'packages:'
  with_lines:
    - 'bash -c "comm -23 <(apt-mark showmanual | sort) <(cat {{ role_path }}/files/ignore.lst | sort)"'

- name: Flatpak
  ansible.builtin.include_role:
    name: flatpak

- name: Snap
  ansible.builtin.include_role:
    name: snap
