---
use:
  - 'app-shells/dash libedit'
  - 'gui-wm/sway grimshot'
  - 'gui-wm/sway tray'
  - 'gui-wm/sway wallpapers'
  - 'media-fonts/noto cjk'
  - 'media-fonts/noto-emoji icons'
  - 'net-wireless/iwd standalone'
  - 'sys-auth/seatd builtin'
  - 'sys-auth/seatd server'
  - 'www-client/firefox-bin wayland'
  - 'x11-terms/alacritty -X'
  - 'x11-terms/alacritty wayland'
  - 'x11-terms/kitty -X'
  - 'x11-terms/kitty wayland'
  - 'app-editors/vim python'
