---
- name: Install
  ansible.builtin.include_role:
    name: package
  vars:
    package_list: '{{ vim_packages }}'
    package_state: '{{ vim_package_state }}'
    package_make_conf: '{{ vim_make_conf }}'
    package_accept_keywords: '{{ vim_package_accept_keywords }}'
    package_env: '{{ vim_package_env }}'
    package_license: '{{ vim_package_license }}'
    package_mask: '{{ vim_package_mask }}'
    package_use: '{{ vim_package_use }}'

- name: Vimrc
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.vimrc'
    create: true
    mode: '0644'
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: '{{ vim_snippet }}'
    state: '{{ vim_package_state }}'

- name: Link Config
  ansible.builtin.include_role:
    name: user
    tasks_from: config
  vars:
    user_config_state: '{{ vim_config_state }}'
    user_config:
      - vim
