source $VIMRUNTIME/defaults.vim

" 2 moving around, searching and patterns
set incsearch
set ignorecase
set smartcase
" 4 displaying text
set scrolloff=5
set nowrap
set list
set listchars+=tab:>\ 
set listchars+=trail:-
set listchars+=nbsp:+
" 5 syntax, highlighting and spelling
set background=dark
set cursorline
" 6 multiple windows
set laststatus=2
set hidden
"11 messages and info
set showcmd
"13 editing text
set undofile
"18 reading and writing files
set autoread
"20 command line editing
set wildmode=list:longest,full
set wildmenu

let mapleader="\<space>"

let $DATA = expand('~/.local/share')
if !($DATA->isdirectory())
  call mkdir($DATA, 'p')
endif
if &runtimepath !~# '/dein.vim'
  let s:dir = 'dein.vim'->fnamemodify(':p')
  if !(s:dir->isdirectory())
    let s:dir = $DATA .. '/vim/repos/github.com/Shougo/dein.vim'
    if !(s:dir->isdirectory())
      execute '!git clone https://github.com/Shougo/dein.vim' s:dir
    endif
  endif
  execute 'set runtimepath^=' .. s:dir->fnamemodify(':p')->substitute('[/\\]$', '', '')
endif

let s:dein_base = $DATA.'/vim/'
let s:dein_src = $DATA.'/vim/repos/github.com/Shougo/dein.vim'
execute 'set runtimepath+=' .. s:dein_src
call dein#begin(s:dein_base)
call dein#add(s:dein_src)
call dein#load_toml('~/.config/vim/dein.toml', #{ lazy: 1 })
call dein#end()
if dein#check_install()
  call dein#install()
endif
