---
- name: '{{ kind }}'
  ansible.builtin.file:
    path: '/etc/portage/package.{{ kind }}'
    mode: '0755'
    state: directory
  become: true

- name: 'Lineinfile /etc/portage/package.{{ kind }}'
  ansible.builtin.lineinfile:
    path: '/etc/portage/package.{{ kind }}/default'
    create: true
    mode: '0644'
    line: '{{ item }}'
  with_items:
    - '{{ lookup("vars", kind) }}'
  become: true

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/main.yml'
    line: "  - '{{ item }}'"
    insertafter: '{{ kind }}:'
  with_lines:
    - >
      sed
      --quiet
      --expression='/^[=>]\?[[:alpha:]]/p'
      '/etc/portage/package.{{ kind }}/default'
