---
- name: Update etc
  ansible.builtin.include_tasks:
    file: etc.yml
  with_items:
    - accept_keywords
    - env
    - license
    - mask
    - use
  loop_control:
    loop_var: kind

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: '{{ item }}'
  with_items:
    - '{{ envvar }}'
  become: true

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: /etc/portage/env/no-mold.conf
    line: 'LDFLAGS="-Wl,-O1 -Wl,--as-needed"'
  become: true

- name: Install
  ansible.builtin.package:
    name: '{{ item }}'
  with_items:
    - '{{ packages }}'
  become: true

- name: Lineinfile
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/main.yml'
    line: '  - {{ item }}'
    insertafter: 'packages:'
  with_lines:
    - >
      sed
      --quiet
      --expression='/^>\?[[:alpha:]]/p'
      /var/lib/portage/world
