---
- name: Install
  ansible.builtin.include_role:
    name: package
  vars:
    package_list: '{{ nushell_packages }}'
    package_state: '{{ nushell_package_state }}'
    package_make_conf: '{{ nushell_make_conf }}'
    package_accept_keywords: '{{ nushell_package_accept_keywords }}'
    package_env: '{{ nushell_package_env }}'
    package_license: '{{ nushell_package_license }}'
    package_mask: '{{ nushell_package_mask }}'
    package_use: '{{ nushell_package_use }}'

- name: Link Config
  ansible.builtin.include_role:
    name: user
    tasks_from: config
  vars:
    user_config_state: '{{ nushell_config_state }}'
    user_config:
      - nushell
