---
- name: Install
  ansible.builtin.include_role:
    name: package
  vars:
    package_list: '{{ neovim_packages }}'
    package_state: '{{ neovim_package_state }}'
    package_make_conf: '{{ neovim_make_conf }}'
    package_accept_keywords: '{{ neovim_package_accept_keywords }}'
    package_env: '{{ neovim_package_env }}'
    package_license: '{{ neovim_package_license }}'
    package_mask: '{{ neovim_package_mask }}'
    package_use: '{{ neovim_package_use }}'

- name: Link Config
  ansible.builtin.include_role:
    name: user
    tasks_from: config
  vars:
    user_config_state: '{{ neovim_config_state }}'
    user_config:
      - nvim
