---
- name: Service
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
  with_items:
    - '{{ lookup("vars", ansible_service_mgr) }}'
  become: true

- name: Group
  ansible.builtin.include_role:
    name: user
    tasks_from: group
    defaults_from: '{{ ansible_service_mgr }}.yml'
