---
- name: 'Ensure /etc/portage/package.{{ kind }}'
  ansible.builtin.file:
    path: '/etc/portage/package.{{ kind }}'
    mode: '0755'
    state: directory
  become: true

- name: 'Lineinfile /etc/portage/package.{{ kind }}'
  ansible.builtin.lineinfile:
    path: '/etc/portage/package.{{ kind }}/default'
    create: true
    mode: '0644'
    line: '{{ item }}'
    state: '{{ package_state }}'
  with_items:
    - '{{ lookup("vars", "package_" + kind) }}'
  become: true

- name: Update defaults
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/portage.yml'
    line: "  - '{{ item }}'"
    insertafter: 'package_{{ kind }}:'
  with_lines:
    - >
      sed
      --quiet
      --expression='/^[=>]\?[[:alpha:]]/p'
      '/etc/portage/package.{{ kind }}/default'
