---
- name: Update etc
  ansible.builtin.include_tasks:
    file: portage_etc.yml
  with_items:
    - '{{ package_etc_files }}'
  when: 'lookup("vars", "package_" + kind) | length > 0'
  loop_control:
    loop_var: kind

- name: Make.conf
  ansible.builtin.lineinfile:
    path: /etc/portage/make.conf
    line: '{{ item }}'
    state: '{{ package_state }}'
  with_items:
    - '{{ package_make_conf }}'
  become: true

- name: Env/no-mold.conf
  ansible.builtin.lineinfile:
    path: /etc/portage/env/no-mold.conf
    line: 'LDFLAGS="-Wl,-O1 -Wl,--as-needed"'
    state: '{{ package_state }}'
  become: true

- name: Install
  ansible.builtin.package:
    name: '{{ item }}'
    state: '{{ package_state }}'
  with_items:
    - '{{ package_list }}'
  become: true

- name: Update defaults
  ansible.builtin.lineinfile:
    path: '{{ role_path }}/defaults/portage.yml'
    line: '  - {{ item }}'
    insertafter: 'package_list:'
  with_lines:
    - >
      sed
      --quiet
      --expression='/^>\?[[:alpha:]]/p'
      /var/lib/portage/world
