---
user_group: []

user_env:
  - CARGO_HOME=$HOME/.local/share/cargo
  - GOPATH=$HOME/.local/share/go
  - RUSTC_WRAPPER=/usr/bin/sccache
  - SCCACHE_DIR=/var/cache/sccache
  - SCCACHE_MAX_FRAME_LENGTH=104857600

user_bash_profile:
  marker: '# {mark} ANSIBLE MANAGED BLOCK'
  block: |
    if [[ -f ~/.profile ]] ; then
      source ~/.profile
    fi

user_profile:
  marker: '# {mark} ANSIBLE MANAGED BLOCK'
  block: |
    if test -z "${XDG_RUNTIME_DIR}"; then
      export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
      if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
      fi
    fi
    for p in $CARGO_HOME $GOPATH
    do
      case ":$PATH:" in
      *:$p/bin:*)
        ;;
      *)
        export PATH=$p/bin:$PATH
      esac
    done

user_config_state: link

user_config:
  - helix
  - sway
  - wofi
